### ISSUE TITLE
getting error on custom domain

### ISSUE THREAD

**Issue by anantsparrow** [i-dream-of-ai/build-a-site#1]
http://www.sparrow.pw/

i tried adding this

**Comment by kitchenbeats** [comment]
ok, you will want to add just the root domain.
sparrow.pw or www.sparrow.pw

No http:// or https://

this will update the bucket name to include your domain name. Then you can point your cname to the full bucket url that includes your domain. 

I suggest using cloudflare, they have a free plan that works nicely.

**Comment by anantsparrow** [comment]
Please check my other mail sir. I have deployed this code but getting error
while generating site

**Comment by anantsparrow** [comment]
![Screenshot 2023-08-10 130630](https://github.com/i-dream-of-ai/build-a-site/assets/38394340/68ff1678-542c-4c6b-bba6-498efe591260)
