### ISSUE TITLE
deployed this code on my server but getting error

### ISSUE THREAD

**Issue by anantsparrow** [i-dream-of-ai/build-a-site#2]
hello there, when trying to update domain name on aws generated url via edit option, it says update failed

**Comment by kitchenbeats** [comment]
Can you give me more information please. What is the error. You can check in the console. 

What is your process to get to this error. 
1. did you deploy this on your own server? 
2. If so, you are using your own AWS account. Did you create a group with a user and assign the correct permissions to that user for the s3 buckets? 

Please give me as much information as you can. Thanks!

**Comment by anantsparrow** [comment]
Hi there can I share you my server login to check?

**Comment by kitchenbeats** [comment]
Hi, happy to help. I probably wont need your server login. Can you give me more details? Are there any errors in the logs that you can share?

**Comment by kitchenbeats** [comment]
Closing issue due to no response.
