### ISSUE TITLE
Stripe Integration & GPT-4

### ISSUE THREAD

**Issue by Inside4ndroid** [i-dream-of-ai/build-a-site#3]
is the stripe integration complete? or maybe i am missing something?

the whole thing works apart from 2 things which are Stripe and the GPT-4 Model in user account settings.
is gpt-4 integrated correctly as when i clicksave i get "There was an error while updating your profile."

now onto Stripe i have setup stripe and supplied the following

#Stripe credentials for user subscriptions
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_live_*******
STRIPE_SECRET_KEY=sk_live_********
STRIPE_WEBHOOK_SECRET=xfx6Q********

but when loggining into user account on website it constantly gives this error :

STRIPE error: You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
failed to add customer {
  _id: '65417d4*********',
  email: 'rob*******',
  model: null,
  role: 'user',
  iat: 1698*****,
  exp: 1701*****,
  jti: '1ea459e*******'
}

can you suggest something i may be doing wrong?

**Comment by kitchenbeats** [comment]
Thank you for the note! 

The model selector should be working. I will take a look at that when I get a chance.

The stripe integration is not complete. Im finishing my current project autobots-ai.com first. Once that is finished I will resume work on this part of the project.

**Comment by Inside4ndroid** [comment]
thanks for taking the time to reply.

I eagerly await you resuming this project. 

Thank You

**Comment by kitchenbeats** [comment]
No problem

**Comment by Inside4ndroid** [comment]
any news on this yet?

i have tried to do it myself with no luck ....
